// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteEstapar.Data.Context;

namespace TesteEstapar.Data.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    partial class MeuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TesteEstapar.Business.Models.Carro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("varchar(7)");

                    b.HasKey("Id");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("TesteEstapar.Business.Models.Manobrista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Manobristas");
                });

            modelBuilder.Entity("TesteEstapar.Business.Models.ResponsavelManobra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CarroId");

                    b.Property<Guid>("ManobristaId");

                    b.HasKey("Id");

                    b.HasIndex("CarroId");

                    b.HasIndex("ManobristaId");

                    b.ToTable("ResponsaveisManobras");
                });

            modelBuilder.Entity("TesteEstapar.Business.Models.ResponsavelManobra", b =>
                {
                    b.HasOne("TesteEstapar.Business.Models.Carro", "Carro")
                        .WithMany("ResponsavelManobras")
                        .HasForeignKey("CarroId");

                    b.HasOne("TesteEstapar.Business.Models.Manobrista", "Manobrista")
                        .WithMany("ResponsavelManobras")
                        .HasForeignKey("ManobristaId");
                });
#pragma warning restore 612, 618
        }
    }
}
